### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by mohamedfarooq** [arkprocoder/DBMS-COVID-BED-SLOT-BOOKING-MINI-PROJECT#2]
cannot run the particular block of code 

new_user = db.engine.execute(f"INSERT INTO `user` (`srfid`,`email`,`dob`) VALUES ('{srfid}','{email}','{encpassword}') ")

this is the line 124 inside the python file

**Comment by arkprocoder** [comment]
Check my code in description

**Comment by mohamedfarooq** [comment]
so what is the solution for this

**Comment by arkprocoder** [comment]
Hey there is no error in this kindly check the syntax match with my code

**Comment by mohamedfarooq** [comment]
oh, i just found out what was wrong, thank you for your help tho
